[fluvel]
DEV_MODE = true

[app]
name = "Fluvel Framework"
version = "0.1.0"
author = "Robotid"
homepage = "https://ww.example.com"
licence = "MIT"
copyright = "Â© 2025 Robotid"

[ui]
theme = "bootstrap"
language = "en"

[window]
title = "MyApp"
size = [1280, 720]
